name: Build and Push EasyDarwin

on:
  push:
    branches: [ "master" ]  # 只要你往 master 分支提交代码，它就自动开始打包

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # 镜像名字会自动变为：ghcr.io/你的用户名/easydarwin-custom:latest
          tags: ghcr.io/zonezzz-zone/easydarwin-custom:latest
